-- Align prop overlay views with current app queries (adds v11/v20+ model fields)
CREATE OR REPLACE VIEW public.np_v_prop_overlay AS
SELECT DISTINCT ON (npp.game_id, npp.player_id, npp.prop_type)
  npp.id,
  npp.game_id,
  npp.player_id,
  npp.prop_type,
  npp.book,
  npp.edge_score,
  npp.confidence,
  npp.risk,
  npp.mu,
  npp.sigma,
  npp.line,
  npp.odds,
  npp.side,
  npp.hit_l10,
  npp.hit_l20,
  npp.streak,
  npp.microbars,
  npp.one_liner,
  npp.pred_ts,
  npp.astro,
  npp.created_at,
  npp.updated_at,
  g.start_time AS game_start_time,
  g.home_abbr,
  g.away_abbr,
  g.league,
  p.name AS player_name,
  p.team AS player_team,
  p.headshot_url,
  npp.edge_score_v11,
  npp.edge_score_v20,
  npp.confidence_tier,
  npp.confidence_adjustment,
  npp.edge_raw,
  npp.p_implied,
  npp.p_model,
  npp.pace_mu_adjust,
  npp.pace_sigma_adjust,
  npp.transit_boost_factor,
  npp.volatility_shift
FROM public.nebula_prop_predictions npp
JOIN public.games g ON g.id = npp.game_id
JOIN public.players p ON p.id = npp.player_id
ORDER BY npp.game_id, npp.player_id, npp.prop_type, npp.pred_ts DESC;

CREATE OR REPLACE VIEW public.np_v_latest_prop_predictions AS
SELECT DISTINCT ON (npp.game_id, npp.player_id, npp.prop_type)
  npp.id,
  npp.game_id,
  npp.player_id,
  npp.prop_type,
  npp.book,
  npp.edge_score,
  npp.confidence,
  npp.risk,
  npp.mu,
  npp.sigma,
  npp.line,
  npp.odds,
  npp.side,
  npp.hit_l10,
  npp.hit_l20,
  npp.streak,
  npp.microbars,
  npp.one_liner,
  npp.pred_ts,
  npp.astro,
  npp.created_at,
  npp.updated_at,
  g.start_time AS game_start_time,
  g.home_abbr,
  g.away_abbr,
  g.league,
  p.name AS player_name,
  p.team AS player_team,
  p.headshot_url,
  npp.edge_score_v11,
  npp.edge_score_v20,
  npp.confidence_tier,
  npp.confidence_adjustment,
  npp.edge_raw,
  npp.p_implied,
  npp.p_model,
  npp.pace_mu_adjust,
  npp.pace_sigma_adjust,
  npp.transit_boost_factor,
  npp.volatility_shift
FROM public.nebula_prop_predictions npp
JOIN public.games g ON g.id = npp.game_id
JOIN public.players p ON p.id = npp.player_id
ORDER BY npp.game_id,
         npp.player_id,
         npp.prop_type,
         CASE WHEN npp.book = 'FanDuel' THEN 0 ELSE 1 END,
         npp.pred_ts DESC;